### ISSUE TITLE
Source Map likely to be incorrect error

### ISSUE THREAD

**Issue by yaldram** [wangzongming/vite-plugin-require#10]
Hello thanks for this plugin I am using this plugin in vite but when I turn on the sourceMap: true option in my build I get this error - `Sourcemap is likely to be incorrect: a plugin (vite-plugin-require) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help`. 

I am using this plugin with vite-pwa and vite-plugin-sentry and for the sentry plugin I need the source map. 

<img width="942" alt="image" src="https://user-images.githubusercontent.com/13429535/168542472-ab8f7761-0cfc-4b42-acf7-ffc814f5bb93.png">

**Comment by wangzongming** [comment]
Thank you for your feedback.
v 1.0.0 resolved
