### ISSUE TITLE
Cannot find module 'webpack'

### ISSUE THREAD

**Issue by xiaweiss** [wangzongming/vite-plugin-require#13]
pnpm install WARN:
<img width="654" alt="image" src="https://user-images.githubusercontent.com/17960084/177242242-4957ed3e-e7e2-4019-ae47-c499947b4928.png">

Vue 2.7.0 project Error:
<img width="849" alt="image" src="https://user-images.githubusercontent.com/17960084/177242206-68fd7ec3-2647-48c5-ac76-cdbe0cc5e4e1.png">

**Comment by wangzongming** [comment]
vite-plugin-require 没有依赖 webpack，你可以看下是不是别的包依赖了。或者你直接安装下 webpack。npm i webpack

**Comment by xiaweiss** [comment]
是 vue-loader 依赖了，vue 2.7.0 没有使用 vue-loader ，用的 @vue/compiler-sfc

**Comment by wangzongming** [comment]
> 是 vue-loader 依赖了，vue 2.7.0 没有使用 vue-loader ，用的 @vue/compiler-sfc

o 对，那你得安装了。这个插件用的 vue-loader 来解析的 vue

**Comment by xiaweiss** [comment]
把所有的 peer 依赖安装后，依然有报错 [plugin:vite-plugin-require] p is not iterable

**Comment by xiaweiss** [comment]
请问下，如果换 rollup-plugin-vue 解析的话，也能实现相同的功能吗？

**Comment by wangzongming** [comment]
> rollup-plugin-vue

只要能把 .vue 文件解析成 ast 就可以
