### ISSUE TITLE
TypeError: vitePluginRequire is not a function

### ISSUE THREAD

**Issue by social-uni** [wangzongming/vite-plugin-require#16]
```
import vitePluginRequire from "vite-plugin-require";

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [vue(), md(), vitePluginRequire()],
    server: {
        host: "0.0.0.0"
    },
    resolve: {
        alias: {
            '@': fileURLToPath(new URL('./src', import.meta.url))
        }
    }
})
```

https://github.com/wangzongming/vite-plugin-require/issues/11

this issues not fix, but issues to be closed,why?

**Comment by wangzongming** [comment]
https://github.com/wangzongming/vite-plugin-require/issues/11#issuecomment-1150543416

**Comment by social-uni** [comment]
> [#11 (comment)](https://github.com/wangzongming/vite-plugin-require/issues/11#issuecomment-1150543416)

If so, is the usage not as described in the documentation?

The following is the content of the document, I follow the document

![image](https://user-images.githubusercontent.com/14007972/187117976-84d97a45-d514-486e-8a65-b367d4cd97d8.png)

If you need to reproduce this problem, you can click on the item below

https://gitee.com/socialuni/vite-plugin-require-issues-17

vite.config.ts

switch be  annotation code 

![image](https://user-images.githubusercontent.com/14007972/187118122-3a925e60-1a82-45da-8205-a1674b5745e9.png)

**Comment by wangzongming** [comment]
Your question and  https://github.com/wangzongming/vite-plugin-require/issues/11#issuecomment-1150543416 unlike，

Your question is #17, right?

**Comment by wangzongming** [comment]
Schedule see  https://github.com/wangzongming/vite-plugin-require/issues/17

**Comment by social-uni** [comment]
> Schedule see #17 

#16 and #17 are two different issues

16 is  TypeError: vitePluginRequire is not a function 

17 is  p is not iterable

**Comment by wangzongming** [comment]
> > Schedule see #17
> 
> #16 and #17 are two different issues
> 
> 16 is TypeError: vitePluginRequire is not a function
> 
> 17 is p is not iterable

Please provide a minimum reproducible example

**Comment by wangzongming** [comment]
No reply for a long time

**Comment by ErrantQuill** [comment]
> 

I am facing the exact same issue.
The minimum reproducible example is to create a new project, install this plugin and add it to the config as in the [original post](https://github.com/wangzongming/vite-plugin-require/issues/16#issue-1353611020).

`npm create vite@latest my-vue-app -- --template vue`
`npm i vite-plugin-require`

and then the config file as follows:

`import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vitePluginRequire from "vite-plugin-require";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    vitePluginRequire()
  ],
})`

I get the same error when I run the above basic project.

**Comment by vsylvestre** [comment]
I am having the exact same issue as described in the previous post. Same setup, but with `react()` instead.

**Comment by sconway** [comment]
I ran into the same issue mentioned here and was able to resolve things by using `vitePluginRequire.default()` instead of vitePluginRequire(). Simplified vite.config.js file:

```
import vitePluginRequire from "vite-plugin-require";

export default {
    plugins: [
		vitePluginRequire.default()
    ]
}
```
