### ISSUE TITLE
p is not iterable

### ISSUE THREAD

**Issue by social-uni** [wangzongming/vite-plugin-require#17]
### demo

https://gitee.com/socialuni/vite-plugin-require-issues-17

### error code 
local
```
import vueLoader from 'vue-loader'

let plugins: parser.ParserPlugin[] = /(.vue)$/.test(id) ? [vueLoader] : ["jsx"];
```
prod

`
let plugins: parser.ParserPlugin[] = /(.vue)$/.test(id) ? [require("vue-loader")] : ["jsx"];
`

### local success code

`
let plugins: parser.ParserPlugin[] = /(.vue)$/.test(id) ? ["vue-loader"] : ["jsx"];
`

### You can switch to use prod vite-plugin-require or local vite-plugin-require by toggling the commented code

vue.config.ts

```
import {fileURLToPath, URL} from 'node:url'

import {defineConfig} from 'vite'
import vue from '@vitejs/plugin-vue'
import md from '@socialuni/vite-plugin-md'
import vitePluginRequire from "./vite-plugin-require/index"
// import vitePluginRequire from "vite-plugin-require"

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [vue(), md(), vitePluginRequire()],
    // plugins: [vue(), md(), vitePluginRequire.default()],
    server: {
        host: "0.0.0.0"
    },
    resolve: {
        alias: {
            '@': fileURLToPath(new URL('./src', import.meta.url))
        }
    }
})

```

same issues https://github.com/wangzongming/vite-plugin-require/issues/14

![image](https://user-images.githubusercontent.com/14007972/187117777-9f60765f-bd8e-4500-8d24-a9ebb7721f43.png)

![image](https://user-images.githubusercontent.com/14007972/187117795-932bd934-ba50-4342-b200-49fe5bfaccf2.png)

**Comment by wangzongming** [comment]
Thanks for the feedback. I will check later. This problem does not appear in my project for the time being.

**Comment by wangzongming** [comment]
Please provide a minimum reproducible example，the case you provided above could not run

**Comment by wangzongming** [comment]
No reply for a long time
