### ISSUE TITLE
升级导致功能缺失

### ISSUE THREAD

**Issue by usercao** [wangzongming/vite-plugin-require#18]
`0.0.8`版本是支持字符串模板写法的，为何后续版本不再支持了呢？现在是锁死在`0.0.8`版本使用中

**Comment by wangzongming** [comment]
字符串模板一直支持的。

**Comment by wangzongming** [comment]
> `0.0.8`版本是支持字符串模板写法的，为何后续版本不再支持了呢？现在是锁死在`0.0.8`版本使用中

字符串模板一直是不支持的，只是支持字符串拼接

**Comment by usercao** [comment]
[test](https://github.com/usercao/ice-test/blob/main/src/pages/Home/index.tsx)复现可以看这个test项目，在`0.0.8`版本中里面所有写法都是没问题的，升级之后就会报错，现在不清楚是哪一个写法不兼容了

**Comment by wangzongming** [comment]
> [test](https://github.com/usercao/ice-test/blob/main/src/pages/Home/index.tsx)复现可以看这个test项目，在`0.0.8`版本中里面所有写法都是没问题的，升级之后就会报错，现在不清楚是哪一个写法不兼容了

案例我看了，
你这个就是字符串模板不支持换成字符串拼接吧。
因为require这个 api 本身第一段地址不能是变量，所以就没支持模板写法，不然判断有点多，或者你可以支持下提个 pr

**Comment by usercao** [comment]
```js
import traverse from '@babel/traverse';
import generate from '@babel/generator';
```

这两个是没有TS类型吗？

**Comment by wangzongming** [comment]
> ```js
> import traverse from '@babel/traverse';
> import generate from '@babel/generator';
> ```
> 
> 这两个是没有TS类型吗？

这两个不需要吧

**Comment by usercao** [comment]
我看现在的代码中是在使用的

**Comment by usercao** [comment]
我看现在的代码中是在使用的
