### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by powershell-js** [wangzongming/vite-plugin-require#19]
不能使用  有很大问题
![1662528686012](https://user-images.githubusercontent.com/43338009/188796329-97485660-829a-4602-a16f-5712fe6a5583.png)

**Comment by wangzongming** [comment]
依赖没有安装。

**Comment by powershell-js** [comment]
![1662529207813](https://user-images.githubusercontent.com/43338009/188797447-9f5f6e7c-1b68-4f3c-8393-b51acfc7c489.png)
安装了也是报错
我是vite3+vue3项目
这是配置项
![1662529266435](https://user-images.githubusercontent.com/43338009/188797569-287e6ae7-8417-4584-b1bb-6493a5af0d97.png)

**Comment by wangzongming** [comment]
你所有依赖都没有安装....  不是那一个依赖问题。

**Comment by wangzongming** [comment]
vue-loader 应该是你装插件时候就自动装的，你现在项目里面也没有装上，你要不就是安装插件时候出啥问题了，导致依赖都没装上

**Comment by powershell-js** [comment]
停用这个插件 我的项目是可以正常运行的  
按理来说 使用插件只要安装这一个插件就好了 为什么还有安装除了这个插件以外的依赖

**Comment by powershell-js** [comment]
我使用的是pnpm  你的插件是存在幽灵依赖问题吧

**Comment by powershell-js** [comment]
![1662529903716](https://user-images.githubusercontent.com/43338009/188798885-9b28220b-7312-4308-899a-31799fdf6a62.png)
换成npm安装依赖还是报错  没有依赖问题了  但是报这个错

**Comment by powershell-js** [comment]
[vue3.zip](https://github.com/wangzongming/vite-plugin-require/files/9503055/vue3.zip)
这是一个demo  你可以看看

**Comment by wangzongming** [comment]
> [vue3.zip](https://github.com/wangzongming/vite-plugin-require/files/9503055/vue3.zip) 这是一个demo 你可以看看

1.0.5 版本中已解决

**Comment by powershell-js** [comment]
![1663048540827](https://user-images.githubusercontent.com/43338009/189820753-3b2cc70d-2f3e-4cde-b209-fe6e7630a006.png)
上面那个demo你运行成功了吗  算了 我换其他的吧
