### ISSUE TITLE
require is hoisted instead of being dynamic

### ISSUE THREAD

**Issue by Agendum** [wangzongming/vite-plugin-require#25]
This results in an error:

```
if (false) {
  require('@/fake');
}
```
**[vite-node] Failed to load /src/fake**

This is indicative of the require implementation not being truly dynamic, and is instead hoisted to the top of the file much like jest.mock and vi.mock.

Expected: The implementation of require would dynamically load the module only when called.

**Comment by wangzongming** [comment]
Yes, the current implementation of require simply uses import instead.
