### ISSUE TITLE
Uncaught SyntaxError: ambiguous indirect export: default

### ISSUE THREAD

**Issue by jonathon-love** [wangzongming/vite-plugin-require#26]
hi,

i'm trying to use `vite-plugin-require` with an existing project which makes use of `require()` and `module.exports =` ... however it looks like this only transforms the `require()` and not the `module.exports =` ... is that correct?

when i launch `vite` and navigate to `localhost:5173` i receive the error `Uncaught SyntaxError: ambiguous indirect export: default`

if i dive down a bit, the problem occurs at a line:

```
import vitePluginRequire_1667865845772_6948 from "/main/utils/clipboardprompt.js";
```

if i then navigate to `http://localhost:5173/main/utils/clipboardprompt.js`, i notice this file hasn't been transformed, and ends with (what remains untouched):

```
module.exports = {
  ClipboardPrompt
};
```

i would have expected `vite-plugin-require` to be transformed input ES6 export statements ... but perhaps i've misunderstood. it doesn't appear than any `module.exports` are rewritten.

could you confirm that i'm understanding this correctly?

with thanks

**Comment by wangzongming** [comment]
This plugin simply converts require to import and does not manipulate the contents of the file.
I think the content of the file should be compiled by vite.
