### ISSUE TITLE
Identifier 'vitePluginRequire_XXXXXXXXXXX_XXXX' has already been declared

### ISSUE THREAD

**Issue by jonathon-love** [wangzongming/vite-plugin-require#27]
hi,

when building my project with `vite-plugin-require`, about 10% of the time i experience the error:

```
Identifier 'vitePluginRequire_XXXXXXXXXXX_XXXX' has already been declared
```

i think this is because there's only 4 digits worth of randomness here:

https://github.com/wangzongming/vite-plugin-require/blob/master/src/index.ts#L81

could we increase it to 8 or 10 digits of randomness? i.e.

```
parseInt(Math.random() * 100000000 + 100 + "")
```

or even better

```
const realPath = `vitePluginRequire_${ Math.random().toString().substring(2) }`;
```

**Comment by wangzongming** [comment]
Thank you very much for your feedback, 
I've changed it in the next version.

vite-plugin-require@1.0.8
