### ISSUE TITLE
tree-shaking does not work

### ISSUE THREAD

**Issue by eleven-net-cn** [wangzongming/vite-plugin-require#28]
The same as: https://github.com/WarrenJones/vite-plugin-require-transform/issues/29

**Comment by wangzongming** [comment]
> Even if set `false`, e.g.:
> 
> ```ts
> if (false) {
>   require('axios');
>   console.log('tree-shaking');
> }
> ```
> 
> `require('axios');` still added at the top, and `console.log('tree-shaking');` has been removed.

Yes, because the address of the require is imported using import at the top of the code during the compilation phase of the code.

require doesn't actually work when the code is running.

At present, I don't have a good idea to solve this problem. Let me think about it.

**Comment by wangzongming** [comment]
Update to  1.1.10，edit config.

vitePluginRequire({ 
  translateType: "importMetaUrl"
}),

**Comment by eleven-net-cn** [comment]
The error still exists with v1.1.10

**Comment by eleven-net-cn** [comment]
The error still exists with v1.1.10, and use specified params (`translateType: "importMetaUrl"`).

**Comment by wangzongming** [comment]
> 

I have passed the test here, please provide the repeat case

**Comment by eleven-net-cn** [comment]
> > 
> 
> I have passed the test here, please provide the repeat case

Here it is: https://github.com/eleven-net-cn/vite-require-plugin-error

**Comment by wangzongming** [comment]
> > > 
> > 
> > 
> > I have passed the test here, please provide the repeat case
> 
> Here it is: https://github.com/eleven-net-cn/vite-require-plugin-error
> 
> The demo is build library mode (vite)
> 
> Before, Tree-shaking does not work fine, but, when I tested it just now, It was worked fine (Tree-Shaking) when set `false`, and does not work fine (require syntax) when set `true`, `require` is converted to `new URL()`.
> 
> Please run `npm run build` to view result (dist).

When 'false', the code is not deleted, but it is not referenced at the top. Components can only do so much.

**Comment by eleven-net-cn** [comment]
The current solution does not solve the problem, the behavior is not as expected.

Suggest reopen this issues until better resolved.

**Comment by wangzongming** [comment]
> The current solution does not solve the problem, the behavior is not as expected.
> 
> Suggest reopen this issues until better resolved.

Running code plug-ins cannot parse. The plug-in will only run during the code compilation phase. If you have a better solution, you can suggest a pr to me

**Comment by eleven-net-cn** [comment]
Until this problem is actually fixed, keep it open to help other users know more information.

I will read the source code carefully to understand more detail.

**Comment by wangzongming** [comment]
> Until this problem is actually fixed, keep it open to help other users know more information.
> 
> I will read the source code carefully to understand more detail.

This is not a plug-in to solve the problem, there is no need to open.
As I said above, plug-ins are only run during the compile code phase.
If you don't cut your code while it's running.

**Comment by eleven-net-cn** [comment]
I see what you mean, this plugin cannot override or resolve it.

It is recommended to specify this case in README, even if this plugin cannot resolve.

This can lead to larger bundle sizes, or debugging code to be bundle into production.

Because most users often done't know these details.

**Comment by wangzongming** [comment]
> I see what you mean, this plugin cannot override or resolve it.
> 
> It is recommended to specify this case in README, even if this plugin cannot resolve.
> 
> This can lead to larger bundle sizes, or debugging code to be bundle into production.
> 
> Because most users often done't know these details.

Well, I'll change the document later.

**Comment by eleven-net-cn** [comment]
Awesome thanks
