### ISSUE TITLE
.vue files breaking when enabling plugin

### ISSUE THREAD

**Issue by shershen08** [wangzongming/vite-plugin-require#29]
I have strange issue with .vue SFCs when trying to use this plugin.
my component code look smth like this:
```
<template>
    <Header @drawer="toggleDrawer" :image="imageHeader"/>
    ... some more template
</template>
 <script>
 ... etc
```

but this is what I  get in the browser

<img width="829" alt="Screenshot 2022-12-02 at 16 16 17" src="https://user-images.githubusercontent.com/1363772/205325511-6b58b7fb-0ee8-47df-a3b1-36055635b8ca.png">

Vue3 + Quazar are used

**Comment by wangzongming** [comment]
There is no problem in our local area, please provide a duplicate case

**Comment by cdll** [comment]
same issue here on `vite@2.9` with `vue@2.6`, `vite-plugin-require@1.1.10`.
