### ISSUE TITLE
Importing vitePluginRequire returns type error

### ISSUE THREAD

**Issue by adriansalgadoa** [wangzongming/vite-plugin-require#30]
You actually have to import vitePluginString and then use it like `vitePluginString.default()`, and by the README I don't think thats the intended usage

**Comment by wangzongming** [comment]
> You actually have to import vitePluginString and then use it like `vitePluginString.default()`, and by the README I don't think thats the intended usage

This is not the intended effect.

In my project, react or vue, I can use the plugin from import directly.
But I don't know why some project can't. 

If possible, could you provide me with a minimum recurrence case? thank you.

Here's an article about it: https://zhidao.baidu.com/question/1119865069850306739.html

**Comment by canaan-yz** [comment]
my case:
latest nodejs, vite ,webstorm, generate project from webstorm gui form. 
Need  write .default() to avoid error at first. 
Strangely, after one success runing, then delete .default(),  the error disapear and project works also fine. 

I don't know why, it seems like vite or webstorm didn't regonize corretly at first? 
either or the difference of export sentence between offical vue plugin and this plugin? I'm not a frontend coder, just a suspect.

**Comment by wangzongming** [comment]
> my case: latest nodejs, vite ,webstorm, generate project from webstorm gui form. Need write .default() to avoid error. After one success runing, then delete .default(), the vite error disapear but chrome console says require undefine that plugin not go into effect. Then I write .default() back.

I'm sorry, man. This is so bad.
