### ISSUE TITLE
This experimental syntax requires enabling one of the following parser plugin(s): "jsx", "flow", "typescript". 

### ISSUE THREAD

**Issue by semdy** [wangzongming/vite-plugin-require#31]
在vite中直接使用报如下错误：[plugin:vite-plugin-require] This experimental syntax requires enabling one of the following parser plugin(s): "jsx", "flow", "typescript". 
vite配置如下：
```javascript
export default defineConfig({
  server: {
    open: true
  },
  build: {
    target: 'es6'
  },
  plugins: [
    vitePluginRequire(),
    uni()
 ]
})
```

**Comment by wangzongming** [comment]
把 build 配置去掉试下。这个应该是配置问题。

**Comment by TheRiver96** [comment]
I Have the same problem

config:
`import { defineConfig } from 'vite'
import createVuePlugin from '@vitejs/plugin-vue'
import vitePluginRequire from 'vite-plugin-require'
import inject from '@rollup/plugin-inject'

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    alias: {
      vue: '@vue/compat'
    }
  },
  plugins: [
    inject({
      $: 'jquery',
      jQuery: 'jquery'
    }),
    vitePluginRequire({
      fileRegex: /(.js?)$/
    }),
    createVuePlugin({
      template: {
        compilerOptions: {
          compatConfig: {
            MODE: 2
          }
        }
      }
    })
  ]
})
`

**Comment by wangzongming** [comment]
可以提供一个可复现的最小项目我看下。 @semdy @TheRiver96

**Comment by magicLaLa** [comment]
这个使用 ts 版还存在，基于 vite4，引用 vue-pdf 时出现，因为 vue-pdf 内部使用了一个 require
