### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by erkanisuf** [wangzongming/vite-plugin-require#32]
import vitePluginRequire from 'vite-plugin-require';
TypeError: vitePluginRequire is not a function
    at file:///C:/Users/Erko/Desktop/secret-project-2023/vite.config.ts.timestamp-1691598601087-0bf64f6d0c889.mjs:7:5
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

vite is :   "vite": "^4.4.0"

**Comment by wangzongming** [comment]
import vitePluginRequire from "vite-plugin-require";

export default {
	plugins: [  
        vitePluginRequire.default()
	],
};
