### ISSUE TITLE
BinaryExpression when using with variable in nuxt

### ISSUE THREAD

**Issue by Aybee5** [wangzongming/vite-plugin-require#33]
When used with a variable in nuxt, I get `Cannot parse given Error object` error or `不支持的: BinaryExpression 组成类型 MemberExpression` error.

Here's a reproduction link on stackblitz https://stackblitz.com/edit/nuxt-starter-ryyjai?file=app.vue, notice if you comment out the last line the app runs

**Comment by wangzongming** [comment]
There is a problem with this situation and I will get around to fixing it as soon as possible.
At present, you can use the following method to solve it.

```
<template>
  <div>
    <img src="@/assets/alert.svg" />
    <img :src="require('@/assets/alert.svg')" />
    <img :src="require(_url)" />
    <!-- <img :src="require('@/assets/' + iconName + '.svg')" /> -->
    <NuxtPage />
  </div>
</template>

<script setup>
const iconName = ref('alert');
// at present， I guess that's the only way to write it
const _url = ref(require('@/assets/alert.svg'));
</script>

```

**Comment by wangzongming** [comment]
```
<template>
  <div> 
    <img :src="require(_url)" /> 
    <NuxtPage />
  </div>
</template>

<script setup>
// This usage is not supported because the plug-in cannot handle variables generated at runtime
const iconName = ref(props.data + ".svg"); 
</script>
```



> Alright, thanks. Looking forward to it 👍🏾
> 
> My actual usage is with a props variable
