### ISSUE TITLE
Source map is off when adding plugin

### ISSUE THREAD

**Issue by maxkopych** [wangzongming/vite-plugin-require#35]
In vue/vite/rails stack sourcemap is completely off. 
Devtool showing incorrect line on error/debug.

vite.config.ts:
```
import {defineConfig} from "vite";
import rubyPlugin from "vite-plugin-ruby";
import vuePlugin from "@vitejs/plugin-vue";
import {nodePolyfills} from "vite-plugin-node-polyfills";
import * as requirePlugin from "vite-plugin-require";
import sassGlobImportPlugin from "vite-plugin-sass-glob-import";

export default defineConfig({
    build: {
        emptyOutDir: true,
        sourcemap: true
    },
    resolve: {
        alias: {
            ...
        },
        extensions: [".js", ".es6", ".ts",  ".json", ".vue"]
    },
    plugins: [
        rubyPlugin(),
        nodePolyfills(),
        vuePlugin({
            template: {
                compilerOptions: {
                    whitespace: "preserve"
                }
            }
        }),
        requirePlugin.default(),
        sassGlobImportPlugin(),
    ],
    clearScreen: false,
    optimizeDeps: {
        include: ["crypto"]
    }
});

```

Example Component:
```
<template>
    <div>
        Home Page
    </div>
</template>

<script>
    export default {
        name: "Home",
        mounted() {
            throw Error("This is error");
        },
    };
</script>
```

This is what it showing me in devtool:

[![enter image description here](https://i.stack.imgur.com/eD0wR.png)](https://i.stack.imgur.com/eD0wR.png)

[![enter image description here][1]][1]

When removing plugin  source map showing correct line

  [1]: https://i.stack.imgur.com/7F6Bz.png

**Comment by wangzongming** [comment]
Fixes have been made in the latest version ，v1.1.12

**Comment by maxkopych** [comment]
After update still have this issue

**Comment by wangzongming** [comment]
> After update still have this issue

I can use your above code locally without error.
Can you directly provide a minimum reproducible case warehouse?

**Comment by maxkopych** [comment]
> > After update still have this issue
> 
> I can use your above code locally without error. Can you directly provide a minimum reproducible case warehouse?

My apology when you build it's working fine. It's something when you running in dev mode. Not sure if it because of plugin or some other settings.

**Comment by wangzongming** [comment]
A version was re-released today (v1.1.13), so try again after the update

**Comment by maxkopych** [comment]
So when you in dev mode and removing sourcemap
```
build: {
    // Clean up old assets on each build
    emptyOutDir: true,
    //sourcemap: true,
},
```
it's show completely off 
![image](https://github.com/wangzongming/vite-plugin-require/assets/10473755/3c70f430-4672-49a1-a300-b67aa997053e)

If I disable your plugin it's works fine:
![image](https://github.com/wangzongming/vite-plugin-require/assets/10473755/e35aa7e1-ec34-4df0-b932-1ac576eda3d3)

If I set `sourcemap: true` with update: dev mode and build works fine. But really slow in dev.

I'm new with vite. But I'm also might think it might be conflict with vue-plugin?

**Comment by wangzongming** [comment]
> actually after restarting server with so `sourcemap: true` works fine. Not sure if it should work without it.

Currently, vite-plugin-require must specify sourcemap: true, otherwise sourcemap will not be generated.

Not setting sourcemap: true does cause error location confusion, so let me check again.
