### ISSUE TITLE
Problem in dev mode

### ISSUE THREAD

**Issue by Josep-Lancharro-Indra** [wangzongming/vite-plugin-require#36]
Hi,
We've recently updated to the new version (1.1.12), and the problem is if you run the project in dev mode but you have the sourcemaps activated on build it doesn't run in dev, and it gives you an error.
![image](https://github.com/wangzongming/vite-plugin-require/assets/117295166/8e716540-f8c7-4850-961b-26ee47992b3a)
![image](https://github.com/wangzongming/vite-plugin-require/assets/117295166/13bb667d-f908-4176-ad41-4c3a9b6aa651)
Can you check it out?
Thanks.

**Comment by wangzongming** [comment]
Thank you for your feedback.
Is it convenient to provide a duplicate case code?

**Comment by wangzongming** [comment]
今天重新发布了一个版本(v1.1.13)，更新后再尝试下

**Comment by wangzongming** [comment]
A version was re-released today (v1.1.13), so try again after the update
