### ISSUE TITLE
require does not work with string variables

### ISSUE THREAD

**Issue by jmatbastos** [wangzongming/vite-plugin-require#37]
Hi 
For some reason it does not work with string variables ...

this works

```
function getImageUrl() {
   const name = 'file.jpg'
    return require( '../assets/img/' + name)
}
```

this does NOT work

```
function getImageUrl(name) {
    return require( '../assets/img/' + name)
}
```

**Comment by jmatbastos** [comment]
and this also does NOT work

return require( `../assets/img/${name}`)

[plugin:vite-plugin-require] Unsupported type: TemplateLiteral

**Comment by wangzongming** [comment]
For you to write this way, 
for the stability of the plug-in consideration. 
The plug-in is currently not implemented.

![image](https://github.com/wangzongming/vite-plugin-require/assets/27466569/81d6ebd6-ece2-461c-ac33-0e1fa33935f4)

**Comment by jmatbastos** [comment]
Ok,  in the mean time I will use this code instead

```
function getImageUrl(name) {
    return new URL(`../assets/img/${name}`, import.meta.url).href
}
```

**Comment by hotdogc1017** [comment]
> For you to write this way,让你这样写， for the stability of the plug-in consideration. 出于插件稳定性的考虑。 The plug-in is currently not implemented. 该插件目前尚未实现。
> 
> ![image](https://private-user-images.githubusercontent.com/27466569/289448117-81d6ebd6-ece2-461c-ac33-0e1fa33935f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDMwNjUsIm5iZiI6MTcwMjU0Mjc2NSwicGF0aCI6Ii8yNzQ2NjU2OS8yODk0NDgxMTctODFkNmViZDYtZWNlMi00NjFjLWFjMzMtMGUxZmEzMzkzNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA4MzI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZmJkOTk0YmY0ZDcyZGQ1YWNhNWVmZjFlMzM4YWIyYjQ1NDg5NWNlMjNmZTM4MjY2N2Y3NjM2YmNiNDcyMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4WeKwcM6SAzPiPoTmf7gzwl3q2Kpp_drpBPvpORPQWo)

Are there any plans to support writing like this in the future?

**Comment by wangzongming** [comment]
> > For you to write this way,让你这样写， for the stability of the plug-in consideration. 出于插件稳定性的考虑。 The plug-in is currently not implemented. 该插件目前尚未实现。
> > ![image](https://private-user-images.githubusercontent.com/27466569/289448117-81d6ebd6-ece2-461c-ac33-0e1fa33935f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDMwNjUsIm5iZiI6MTcwMjU0Mjc2NSwicGF0aCI6Ii8yNzQ2NjU2OS8yODk0NDgxMTctODFkNmViZDYtZWNlMi00NjFjLWFjMzMtMGUxZmEzMzkzNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA4MzI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZmJkOTk0YmY0ZDcyZGQ1YWNhNWVmZjFlMzM4YWIyYjQ1NDg5NWNlMjNmZTM4MjY2N2Y3NjM2YmNiNDcyMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4WeKwcM6SAzPiPoTmf7gzwl3q2Kpp_drpBPvpORPQWo)
> 
> Are there any plans to support writing like this in the future?

目前暂时没有这个计划哦。字符串模板加进去后情况会比较多。
