### ISSUE TITLE
文件引入后报错 his experimental syntax requires enabling one of the following parser plugin(s): "jsx", "flow", "typescript". (1:0)

### ISSUE THREAD

**Issue by sxdlh123** [wangzongming/vite-plugin-require#39]
![微信截图_20240102160051](https://github.com/wangzongming/vite-plugin-require/assets/54256708/2f30920b-24e1-46da-8ad9-0fee43ca3c6f)
![微信截图_20240102160109](https://github.com/wangzongming/vite-plugin-require/assets/54256708/44da1882-d570-4cc5-955d-1f8e29ff8814)

**Comment by wangzongming** [comment]
提供一个复现案例我看下
