### ISSUE TITLE
Issue with typescript

### ISSUE THREAD

**Issue by euberdeveloper** [wangzongming/vite-plugin-require#40]
About the FAQ, of using:

```javascript
import vitePluginRequire from "vite-plugin-require";

export default {
	plugins: [  
        vitePluginRequire.default()
	],
};
```

* I don't know why it must be like that
* With typescript I have to put `(vitePluginRequire as any).default()` otherwise it fails

**Comment by wangzongming** [comment]
There is this problem in vite4, and I have not explored the specific reasons.
export default is a function so .default() gets an error in Typescript.
![image](https://github.com/wangzongming/vite-plugin-require/assets/27466569/000c87c1-fe15-4ddc-b61d-0cde0eb0ea64)

**Comment by euberdeveloper** [comment]
Does this mean that the problem is with vite 4 and forwards (also 5), or backward (so all the versions before 5)?
