### ISSUE TITLE
Vite5 无法使用

### ISSUE THREAD

**Issue by idleRain** [wangzongming/vite-plugin-require#43]
启动时候会报错：TypeError: vitePluginRequire is not a function

**Comment by wangzongming** [comment]
应该要和 vite4一样用
  // vite4
  // vitePluginRequire.default()

**Comment by alamhubb** [comment]
> 应该要和 vite4一样用 // vite4 // vitePluginRequire.default()

两种方法我都试了，不行 https://github.com/wangzongming/vite-plugin-require/issues/45
