### ISSUE TITLE
模版字符串中有变量不支持

### ISSUE THREAD

**Issue by zhou94** [wangzongming/vite-plugin-require#44]
require(`xxx/result_${isFail ? 'fail' : 'processing'}.png`) 类似的模版字符串不支持

**Comment by wangzongming** [comment]
暂时还不支持表达式和字符串模板写法
![image](https://github.com/wangzongming/vite-plugin-require/assets/27466569/b8844c31-31b7-4b77-8b8f-b2b5d8f80b97)
