### ISSUE TITLE
Vue: Property default does not exist on type

### ISSUE THREAD

**Issue by m5ultra** [wangzongming/vite-plugin-require#48]
<img width="1093" alt="image" src="https://github.com/user-attachments/assets/a79f6b42-89b9-4c3b-8bbf-8d951771b065">
<img width="1235" alt="image" src="https://github.com/user-attachments/assets/861b8d21-3cb8-4fe0-8ecc-b182989dbcb5">

**Comment by m5ultra** [comment]
webstorm vscode都报错

**Comment by wangzongming** [comment]
尝试 
```
import * as vitePluginRequire from "vite-plugin-require";
```

或者
```
```
import  vitePluginRequireJs from "vite-plugin-require";

const vitePluginRequire: any = vitePluginRequireJs;

// ...
vitePluginRequire({})
// ...
```

**Comment by m5ultra** [comment]
(vitePluginRequire as any).default()
