### ISSUE TITLE
Update vite 6

### ISSUE THREAD

**Issue by NeluQi** [wangzongming/vite-plugin-require#51]
node_modules/vite
npm error   dev vite@"6.0.3" from the root project
npm error   peer vite@"^6.0.0" from @vitejs/plugin-legacy@6.0.0
npm error   node_modules/@vitejs/plugin-legacy
npm error     dev @vitejs/plugin-legacy@"6.0.0" from the root project
npm error   7 more (@vitejs/plugin-vue, @vitejs/plugin-vue-jsx, ...)
npm error

 Conflicting peer dependency: vite@5.4.11
npm error node_modules/vite
npm error   peer vite@"^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0" from vite-plugin-require@1.2.14
npm error   node_modules/vite-plugin-require
npm error     dev vite-plugin-require@"1.2.14" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.

**Comment by wangzongming** [comment]
try `npm i vite-plugin-require  --force` 

This can only install plugins and I'm not sure he can run correctly.

**Comment by NeluQi** [comment]
> try `npm i vite-plugin-require --force`
> 
> This can only install plugins and I'm not sure he can run correctly.

This is bad practice, I did it this way for now, but it's better to update

**Comment by wangzongming** [comment]
> > try `npm i vite-plugin-require --force`
> > This can only install plugins and I'm not sure he can run correctly.
> 
> This is bad practice, I did it this way for now, but it's better to update

I will update it later because it will take some time to test compatibility issues.
