### ISSUE TITLE
需要使用vitePluginRequire.default()

### ISSUE THREAD

**Issue by xd-shadow** [wangzongming/vite-plugin-require#6]
```
import vitePluginRequire from 'vite-plugin-require'

console.log(vitePluginRequire)
export default {
  plugins: [
    vue(),
    ssr(),
    vitePluginRequire.default({
      // @fileRegex RegExp
      // optional：default file processing rules are as follows
      // fileRegex:/(.jsx?|.tsx?|.vue)$/
    }),
  ],
}
```
需要这样使用，直接使用 vitePluginRequire()  会报错 vitePluginRequire is not a function

**Comment by wangzongming** [comment]
是不是你的什么依赖不是最新的。我这里是正常的。
![image](https://user-images.githubusercontent.com/27466569/142843147-dc4910ec-86ed-43b3-8268-bf31896fd1cc.png)

**Comment by xd-shadow** [comment]
暂时没想到，应该不是依赖的问题

**Comment by Dragon-Fish** [comment]
![](https://user-images.githubusercontent.com/44761872/180905649-7b1af61d-6cc8-477d-b629-793cdfa2f6d4.png)

Meet the same issue
