### ISSUE TITLE
build之后只是把相对路径变成绝对路径

### ISSUE THREAD

**Issue by xd-shadow** [wangzongming/vite-plugin-require#7]
正确的应该是
![image](https://user-images.githubusercontent.com/35983043/142843317-eabbb4aa-154f-4565-baf0-fad7c1efeac5.png)
实际情况是
![image](https://user-images.githubusercontent.com/35983043/142843552-a09f7b48-8ced-46e1-a781-7c5609318368.png)

```
<img :src="photo">

 const photo = require('./img/1.png'),

```

**Comment by wangzongming** [comment]
感谢反馈，0.0.7版本中 已修复，
