### ISSUE TITLE
无法找到模块“vite-plugin-require”的声明文件。

### ISSUE THREAD

**Issue by usercao** [wangzongming/vite-plugin-require#8]
## 无法找到模块“vite-plugin-require”的声明文件。
![image](https://user-images.githubusercontent.com/13760476/148693578-706496dd-3002-49d4-ba7f-5609e4b2816f.png)
## TS项目中无法使用
![image](https://user-images.githubusercontent.com/13760476/148693570-ef52ce5d-7942-4c56-972a-2d8db29e1650.png)

**Comment by wangzongming** [comment]
第一个提示我随后测试下。
第二个提示 require 需要你自己全局定义一个声明（在你项目根目录添加一个 index.d.ts 里面加一下 require 定义）。

**Comment by wangzongming** [comment]
第一个问题确实是忘记打包声明文件了。在 0.0.8 版本中已打包声明文件。第一个问题确实是忘记打包声明文件了。在 0.0.8 版本中已打包声明文件。
