### ISSUE TITLE
可以支持别名吗

### ISSUE THREAD

**Issue by wowohuai** [wangzongming/vite-plugin-require#9]

**Comment by usercao** [comment]
@wowohuai @wangzongming 请问现在如何支持动态别名引入？例如
```js
const message = 'dark' | 'light'
require(`@/assets/images/layouts/${message}.svg`)
```

**Comment by wangzongming** [comment]
> ```js
> 
> ```

目前插件没有支持别名，后续会支持的~（暂时么有时间升级🤓）。

**Comment by wangzongming** [comment]
> @wowohuai @wangzongming 请问现在如何支持动态别名引入？例如
> 
> ```js
> const message = 'dark' | 'light'
> require(`@/assets/images/layouts/${message}.svg`)
> ```


目前插件没有支持别名，后续会支持的~（暂时么有时间升级🤓）。
